import { ClipboardList,
  ArchiveX,
  BadgeCheck,
  BarChart3,
  Bell,
  Building,
  Building2,
  CircleDollarSign,
  Contact,
  DoorClosed,
  DoorOpen,
  EyeOff,
  CalendarCheck,
  CalendarDays,
  Flame,
  HandCoins,
  Inbox,
  KeyRound,
  Handshake,
  House,
  LineChart,
  ListChecks,
  Map as MapIcon,
  Rocket,
  Settings,
  Snowflake,
  Sparkles,
  Tag,
  Target,
  TrendingUp,
  UserRound,
  UserSearch,
  Users,
  UsersRound,
  Wallet,
  MessagesSquare,
  type LucideProps,
} from "lucide-react";
import type { MenuKey, NavKey } from "@/lib/nav";

const ICONS: Record<NavKey | MenuKey, React.ComponentType<LucideProps>> = {
  home: House,
  plan: Rocket,
  business: Wallet,
  territory: MapIcon,
  brix: Sparkles,
  tasks: ListChecks,
  calendar: CalendarDays,
  deals: Handshake,
  chat: MessagesSquare,
  properties: Building2,
  myProperties: Building2,
  soldProperties: CircleDollarSign,
  withdrawnProperties: ArchiveX,
  colleaguesProperties: Building,
  offMarketProperties: EyeOff,
  openHouses: DoorOpen,
  clients: Users,
  buyers: HandCoins,
  sellers: Tag,
  tenants: KeyRound,
  landlords: DoorClosed,
  coldContacts: Snowflake,
  partners: Contact,
  signals: Flame,
  followup: CalendarCheck,
  contacts: Inbox,
  stats: BarChart3,
  statsBroker: UserRound,
  statsMarket: LineChart,
  market: TrendingUp,
  partnerSearches: UserSearch,
  closedDeals: BadgeCheck,
  team: UsersRound,
  goals: Target,
  teamReport: ClipboardList,
  notifications: Bell,
  profile: UserRound,
  settings: Settings,
  // the sections
  day: CalendarCheck,
  insights: BarChart3,
  path: Rocket,
};

export function NavIcon({ name, ...props }: { name: NavKey | MenuKey } & LucideProps) {
  const Icon = ICONS[name];
  return <Icon {...props} />;
}
