import {
  BadgeCheck,
  BarChart3,
  Bell,
  Building2,
  DoorOpen,
  CalendarCheck,
  CalendarDays,
  Flame,
  Inbox,
  Handshake,
  House,
  LineChart,
  ListChecks,
  Map as MapIcon,
  Rocket,
  Settings,
  Sparkles,
  Target,
  TrendingUp,
  UserRound,
  UserSearch,
  Users,
  UsersRound,
  Wallet,
  type LucideProps,
} from "lucide-react";
import type { MenuKey, NavKey } from "@/lib/nav";

const ICONS: Record<NavKey | MenuKey, React.ComponentType<LucideProps>> = {
  home: House,
  plan: Rocket,
  business: Wallet,
  territory: MapIcon,
  brix: Sparkles,
  tasks: ListChecks,
  calendar: CalendarDays,
  deals: Handshake,
  properties: Building2,
  openHouses: DoorOpen,
  clients: Users,
  signals: Flame,
  followup: CalendarCheck,
  contacts: Inbox,
  stats: BarChart3,
  statsBroker: UserRound,
  statsMarket: LineChart,
  market: TrendingUp,
  partnerSearches: UserSearch,
  closedDeals: BadgeCheck,
  team: UsersRound,
  goals: Target,
  notifications: Bell,
  profile: UserRound,
  settings: Settings,
  // the sections
  day: CalendarCheck,
  insights: BarChart3,
  path: Rocket,
};

export function NavIcon({ name, ...props }: { name: NavKey | MenuKey } & LucideProps) {
  const Icon = ICONS[name];
  return <Icon {...props} />;
}
